### ISSUE TITLE
Installation Error: The specified location-constraint is not valid -Service: S3, Status Code: 400

### ISSUE THREAD

**Issue by CarlosRigil** [awslabs/aws-saas-boost#128]
I have been trying to deploy AWS SaaS Boost following the guide:
https://github.com/awslabs/aws-saas-boost/blob/main/docs/install_using_cloud9.md 

After completing all the prerequisites and running the install.sh script, i got the following error.
===========================================================
Checking for necessary AWS service linked roles
Creating S3 artifacts bucket
===========================================================
Installation Error: The specified location-constraint is not valid (Service: S3, Status Code: 400, Request ID: PNVGXZ1TWDFSZFHN, Extended Request ID: ljBXVMnulTSIk8tB1xPqeIsBbg0f6JcPZ580Z1UO2pc8z80ZGkIDfoi04xiCUA8tW6PfS65v8eM=)
Please see detailed log file saas-boost-install.log

My user account has full administrator rights.

### Reproduction Steps
Server: Cloud9AmazonLinux2
Maven: Apache Maven 3.5.2
Yarn: 1.22.11
Java: Corretto-11.0.12.7.1
Node: v14.17.6

Would you like to continue the installation with the following options?
AWS Account: <redacted>
AWS Region: us-east-1
AWS SaaS Boost Environment Name: dev
Admin Email Address: <redacted>
Install optional Analytics Module: true
Amazon QuickSight user for Analytics Module: <redacted>
Setup AWS Directory Service for FSx for Windows File Server: false

Continue (y or n)? y

### What did you expect to happen?
Finish installation proccess

Fully deploy Saas boost
### What actually happened?
===========================================================
Installing AWS SaaS Boost
===========================================================
Checking for necessary AWS service linked roles
Creating S3 artifacts bucket
===========================================================
Installation Error: The specified location-constraint is not valid (Service: S3, Status Code: 400, Request ID: NMD8A28AES-partially-redacted, Extended Request ID: lLNxNCiVU21TZCoi18GNuf3j7YvOFPk5xj-partially-redacted
Please see detailed log file saas-boost-install.log

2021-09-23 15:59:30.673  ERROR SaaSBoostInstall - software.amazon.awssdk.services.s3.model.S3Exception: The specified location-constraint is not valid (Service: S3, Status Code: 400, Request ID: FAGJZ1TJDNA-partially-redacted, Extended Request ID: hQIWJJHjlBAngG193OYF1WTmZLU16DqmsLsK7Jhn1-partially-redacted

### Environment

  - **AWS Region  :** us-east-1
  - **AWS SaaS Boost Version :**
  2021-09-23 15:58:52.566  INFO  SaaSBoostInstall - 330525e-dirty, Commit time: 2021-09-15T21:40:19+0000
2021-09-23 15:58:52.570  WARN  SaaSBoostInstall - Setting version to 330525e because the repository is untagged.
2021-09-23 15:58:54.122  INFO  SaaSBoostInstall - ===========================================================
2021-09-23 15:58:54.123  INFO  SaaSBoostInstall - Welcome to the AWS SaaS Boost Installer
2021-09-23 15:58:54.124  INFO  SaaSBoostInstall - Installer Version: 330525e
2021-09-23 15:58:54.124  INFO  SaaSBoostInstall - Checking maven, yarn and AWS CLI...
2021-09-23 15:58:54.125  INFO  SaaSBoostInstall - Executing Commands: mvn -version
2021-09-23 15:58:54.464  INFO  SaaSBoostInstall - Apache Maven 3.5.2 (138edd61fd100ec658bfa2d307c43b76940a5d7d; 2017-10-18T07:58:13Z)
2021-09-23 15:58:54.464  INFO  SaaSBoostInstall - Maven home: /usr/share/apache-maven
2021-09-23 15:58:54.465  INFO  SaaSBoostInstall - Java version: 11.0.12, vendor: Amazon.com Inc.
2021-09-23 15:58:54.465  INFO  SaaSBoostInstall - Java home: /usr/lib/jvm/java-11-amazon-corretto.x86_64
2021-09-23 15:58:54.465  INFO  SaaSBoostInstall - Default locale: en_US, platform encoding: UTF-8
2021-09-23 15:58:54.466  INFO  SaaSBoostInstall - OS name: "linux", version: "4.14.246-187.474.amzn2.x86_64", arch: "amd64", family: "unix"
2021-09-23 15:58:54.474  INFO  SaaSBoostInstall - Executing Commands: yarn -version
2021-09-23 15:58:54.648  INFO  SaaSBoostInstall - 1.22.11
2021-09-23 15:58:54.657  INFO  SaaSBoostInstall - Executing Commands: aws --version
2021-09-23 15:58:54.996  INFO  SaaSBoostInstall - Executing Commands: aws sts get-caller-identity
  - **Workload OS  (Linux or Windows) :**
Cloud9AmazonLinux2
### Other

2021-09-23 15:59:30.673  ERROR SaaSBoostInstall - software.amazon.awssdk.services.s3.model.S3Exception: The specified location-constraint is not valid (Service: S3, Status Code: 400, Request ID: FAGJZ1TJDNA-partially-redacted, Extended Request ID: hQIWJJHjlBAngG193OYF1WTmZLU16DqmsLsK7Jhn1-partially-redacted
        at software.amazon.awssdk.protocols.xml.internal.unmarshall.AwsXmlPredicatedResponseHandler.handleErrorResponse(AwsXmlPredicatedResponseHandler.java:156)
        at software.amazon.awssdk.protocols.xml.internal.unmarshall.AwsXmlPredicatedResponseHandler.handleResponse(AwsXmlPredicatedResponseHandler.java:106)
        at software.amazon.awssdk.protocols.xml.internal.unmarshall.AwsXmlPredicatedResponseHandler.handle(AwsXmlPredicatedResponseHandler.java:84)
        at software.amazon.awssdk.protocols.xml.internal.unmarshall.AwsXmlPredicatedResponseHandler.handle(AwsXmlPredicatedResponseHandler.java:42)
        at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler$Crc32ValidationResponseHandler.handle(AwsSyncClientHandler.java:94)
        at software.amazon.awssdk.core.internal.handler.BaseClientHandler.lambda$successTransformationResponseHandler$5(BaseClientHandler.java:229)
        at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:40)
        at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:30)
        at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
        at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:73)
        at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:42)
        at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:77)
        at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:39)
        at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:50)
        at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:36)
        at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:64)
        at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:34)
        at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
        at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:56)
        at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:36)
        at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.executeWithTimer(ApiCallTimeoutTrackingStage.java:80)
        at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:60)
        at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:42)
        at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:48)
        at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:31)
        at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
        at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
        at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:37)
        at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:26)
        at software.amazon.awssdk.core.internal.http.AmazonSyncHttpClient$RequestExecutionBuilderImpl.execute(AmazonSyncHttpClient.java:193)
        at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.invoke(BaseSyncClientHandler.java:128)
        at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.doExecute(BaseSyncClientHandler.java:154)
        at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.lambda$execute$1(BaseSyncClientHandler.java:107)
        at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.measureApiCallSuccess(BaseSyncClientHandler.java:162)

--- 

This is :bug: Bug Report

**Comment by PoeppingT** [comment]
Hi @CarlosRigil , thanks for the report! Can you just answer a few questions to help me reproduce this issue:
1. At what point in the process did you see this failure? Did you ever see a message like `Awaiting CloudFormation Stack sb-dev to complete.  Sleep 1 minute(s)...`?
2. Can you verify that your Cloud9 environment (the EC2 instance hosting the environment) was provisioned in us-east-1?
3. It looks like you've obfuscated some information from the Installer's confirmation (totally fine). Can you just confirm for me that your selections during the install process were like the below? Or, if they were different, how were they different?
```
===========================================================
 1. New AWS SaaS Boost install.
 2. Install Metrics and Analytics into existing AWS SaaS Boost deployment.
 3. Update Web Application for existing AWS SaaS Boost deployment.
 4. Update existing AWS SaaS Boost deployment.
 5. Delete existing AWS SaaS Boost deployment.
 6. Exit installer.
Please select an option to continue (1-6): 1
Directory path of Saas Boost download (Press Enter for '<saas-boost install directory>'): 
Enter name of the AWS SaaS Boost environment to deploy (Ex. dev, test, uat, prod, etc.): dev
Enter the email address for your AWS SaaS Boost administrator: <your email address>
Enter the email address address again to confirm: <your email address>
Would you like to install the metrics and analytics module of AWS SaaS Boost (y or n)? y
Would you like to setup Amazon Quicksight for the Analytics module? You must have already registered for Quicksight in your account (y or n)? n
If your application runs on Windows and uses a shared file system, Active Directory is required.
Would you like to provision AWS Directory Service to use with FSx for Windows File Server (y or n)? n

===========================================================
```

**Comment by CarlosRigil** [comment]
Hi @PoeppingT  , thanks for your quick response, here my rest of my info:

**1.-At what point in the process did you see this failure? Did you ever see a message like Awaiting CloudFormation Stack sb-dev to complete. Sleep 1 minute(s)...?**

I don't see any message about "Awaiting CloudFormation Stack sb-dev to complete..." I process got interrupted just after the output that says "Creating S3 artifacts bucket"

Right after that, the error described on my post got displayed.

**2.-Can you verify that your Cloud9 environment (the EC2 instance hosting the environment) was provisioned in us-east-1?**

It was created on us-east-1, and confirmed running describe-instance from AWS CLI (see output below)

                    "Placement": {
                        "AvailabilityZone": "us-east-1e",
                        "GroupName": "",
                        "Tenancy": "default"
                    },

**3.-It looks like you've obfuscated some information from the Installer's confirmation (totally fine). Can you just confirm for me that your selections during the install process were like the below? Or, if they were different, how were they different?**

The selection were as described, I am just selecting option #1 (New AWS SaaS Boost Install.)
then I confirm the path of the  Saas Boost download directory
Then, I select the name of the environment, which I am typing "dev"
later, I type twice my email address and I confirm that I want to install Analytics
system asks if I want to setup QuickSight and I reply "y" (because I already did the QuickSight setup on us-east-1 before hand using same user account)
the I respond "n" to the question if I want to setup AWS Directory Service.

***NOTE*** I have replicated same issue provisioning a new EC2 Instance with Amazon Linux 2, installing same tooling versions used for Cloud9. I just wanted to use a brand new EC2 instance and replicate the issue.
After repeating same steps, I am getting same error. 
this new EC2 instance is also located in us-east-1.

**Comment by PoeppingT** [comment]
Thanks for the report @CarlosRigil ! I have reproduced the issue in us-east-1 as well: in fact you don't need to install any optional modules in saas-boost for this to happen. The issue lies with the specification of `BucketLocationConstraint` in [SaaSBoostInstall](https://github.com/awslabs/aws-saas-boost/blob/main/installer/src/main/java/com/amazon/aws/partners/saasfactory/saasboost/SaaSBoostInstall.java#L1708) when creating the S3 bucket:
```
CreateBucketResponse createResponse = s3.createBucket(request -> request
    .createBucketConfiguration(
        config -> config.locationConstraint(BucketLocationConstraint.fromValue(AWS_REGION.id()))
    )
    .bucket(this.s3ArtifactBucket)
);
```
S3 buckets are created in us-east-1 by default, so placing a `BucketLocationConstraint` specifying us-east-1 doesn't make sense.

If you would like to take a shot at fixing this yourself, go for it! You can fork `aws-saas-boost`, make the change yourself, test it, then open a PR from your fork against the main repository. If not, one of us in the community will get to it soon.

**Comment by brtrvn** [comment]
Ah, good old S3 not acting like any other service (because it was the first!). Be sure that the fix retains the current functionality when the region **_is not_** us-east-1.

**Comment by CarlosRigil** [comment]
Hi @PoeppingT, I did what you suggested, and now the installation works!

**Comment by PoeppingT** [comment]
We still want to fix this in main, so reopening this issue.
