### ISSUE TITLE
SaaS Boost installation fails into new clean AWS env on SaaS Boost Metrics and Analytics CFT

### ISSUE THREAD

**Issue by LiamRandall** [awslabs/aws-saas-boost#144]
The SaaS boost installation fails when trying to setup AWS SaaS Boost Metrics and Analytics Module module with an error about the CFT missing ParameterKey PrivateSubnet1 

### Reproduction Steps

New AWS Environment, Quicksight configured per guide linked here:
https://github.com/awslabs/aws-saas-boost/blob/main/docs/getting-started.md

Quicksight configured per Step-3, part 8 Standard Installation

### What did you expect to happen?

The initial installation to complete.

### What actually happened?

```
2021-10-31 10:29:30.481  INFO  SaaSBoostInstall - ===========================================================
2021-10-31 10:29:30.481  INFO  SaaSBoostInstall - Installing AWS SaaS Boost Metrics and Analytics Module
2021-10-31 10:29:30.481  INFO  SaaSBoostInstall - ===========================================================
2021-10-31 10:29:30.589  INFO  SaaSBoostInstall - Generating new random RedShift password for Analytics
2021-10-31 10:29:30.589  INFO  SaaSBoostInstall - Saving RedShift password secret to Parameter Store
2021-10-31 10:29:30.686  INFO  SaaSBoostInstall - Redshift Database User Password stored in secure SSM Parameter: /saas-boost/test/REDSHIFT_MASTER_PASSWORD
2021-10-31 10:29:30.686  INFO  SaaSBoostInstall - Creating CloudFormation stack sb-test-analytics for Analytics Module
2021-10-31 10:29:30.686  INFO  SaaSBoostInstall - Creating CloudFormation stack sb-test-analytics with database name sb_analytics_test
2021-10-31 10:29:30.686  INFO  SaaSBoostInstall - createMetricsStack::stack sb-test-analytics
2021-10-31 10:29:30.752  ERROR SaaSBoostInstall - cloudformation error
software.amazon.awssdk.services.cloudformation.model.CloudFormationException: ParameterValue for ParameterKey PrivateSubnet1 is required (Service: CloudFormation, Status Code: 400, Request ID: cf9c538b-76ad-49f3-a502-3b2a308ffab0, Extended Request ID: null)
        at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleErrorResponse(CombinedResponseHandler.java:123) ~[SaaSBoostInstall-1.0.0-shaded.jar:?]
        at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleResponse(CombinedResponseHandler.java:79) ~[SaaSBoostInstall-1.0.0-shaded.jar:?]
        at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:59) ~[SaaSBoostInstall-1.0.0-shaded.jar:?]
        at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:40) ~[SaaSBoostInstall-1.0.0-shaded.jar:?]
        at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:40) ~[SaaSBoostInstall-1.0.0-shaded.jar:?]
        at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:30) ~[SaaSBoostInstall-1.0.0-shaded.jar:?]
        at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206) ~[SaaSBoostInstall-1.0.0-shaded.jar:?]
        at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:73) ~[SaaSBoostInstall-1.0.0-shaded.jar:?]
        at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:42) ~[SaaSBoostInstall-1.0.0-shaded.jar:?]
        at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:78) ~[SaaSBoostInstall-1.0.0-shaded.jar:?]
        at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:40) ~[SaaSBoostInstall-1.0.0-shaded.jar:?]
        at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:50) ~[SaaSBoostInstall-1.0.0-shaded.jar:?]
        at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:36) ~[SaaSBoostInstall-1.0.0-shaded.jar:?]
        at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:81) ~[SaaSBoostInstall-1.0.0-shaded.jar:?]
        at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:36) ~[SaaSBoostInstall-1.0.0-shaded.jar:?]
        at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206) ~[SaaSBoostInstall-1.0.0-shaded.jar:?]
        at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:56) ~[SaaSBoostInstall-1.0.0-shaded.jar:?]
        at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:36) ~[SaaSBoostInstall-1.0.0-shaded.jar:?]
        at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.executeWithTimer(ApiCallTimeoutTrackingStage.java:80) ~[SaaSBoostInstall-1.0.0-shaded.jar:?]
        at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:60) ~[SaaSBoostInstall-1.0.0-shaded.jar:?]
        at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:42) ~[SaaSBoostInstall-1.0.0-shaded.jar:?]
        at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:48) ~[SaaSBoostInstall-1.0.0-shaded.jar:?]
        at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:31) ~[SaaSBoostInstall-1.0.0-shaded.jar:?]
        at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206) ~[SaaSBoostInstall-1.0.0-shaded.jar:?]
        at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206) ~[SaaSBoostInstall-1.0.0-shaded.jar:?]
        at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:37) ~[SaaSBoostInstall-1.0.0-shaded.jar:?]
        at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:26) ~[SaaSBoostInstall-1.0.0-shaded.jar:?]
        at software.amazon.awssdk.core.internal.http.AmazonSyncHttpClient$RequestExecutionBuilderImpl.execute(AmazonSyncHttpClient.java:193) ~[SaaSBoostInstall-1.0.0-shaded.jar:?]
        at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.invoke(BaseSyncClientHandler.java:103) ~[SaaSBoostInstall-1.0.0-shaded.jar:?]
        at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.doExecute(BaseSyncClientHandler.java:167) ~[SaaSBoostInstall-1.0.0-shaded.jar:?]
        at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.lambda$execute$1(BaseSyncClientHandler.java:82) ~[SaaSBoostInstall-1.0.0-shaded.jar:?]
        at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.measureApiCallSuccess(BaseSyncClientHandler.java:175) ~[SaaSBoostInstall-1.0.0-shaded.jar:?]
        at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:76) ~[SaaSBoostInstall-1.0.0-shaded.jar:?]
        at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:45) ~[SaaSBoostInstall-1.0.0-shaded.jar:?]
        at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:56) ~[SaaSBoostInstall-1.0.0-shaded.jar:?]
        at software.amazon.awssdk.services.cloudformation.DefaultCloudFormationClient.createStack(DefaultCloudFormationClient.java:656) ~[SaaSBoostInstall-1.0.0-shaded.jar:?]
        at com.amazon.aws.partners.saasfactory.saasboost.SaaSBoostInstall.createMetricsStack(SaaSBoostInstall.java:1567) [SaaSBoostInstall-1.0.0-shaded.jar:?]
        at com.amazon.aws.partners.saasfactory.saasboost.SaaSBoostInstall.installAnalyticsModule(SaaSBoostInstall.java:625) [SaaSBoostInstall-1.0.0-shaded.jar:?]
        at com.amazon.aws.partners.saasfactory.saasboost.SaaSBoostInstall.installSaaSBoost(SaaSBoostInstall.java:365) [SaaSBoostInstall-1.0.0-shaded.jar:?]
        at com.amazon.aws.partners.saasfactory.saasboost.SaaSBoostInstall.start(SaaSBoostInstall.java:200) [SaaSBoostInstall-1.0.0-shaded.jar:?]
        at com.amazon.aws.partners.saasfactory.saasboost.SaaSBoostInstall.main(SaaSBoostInstall.java:150) [SaaSBoostInstall-1.0.0-shaded.jar:?]
```

### Environment

  - **AWS Region  :**
  - **AWS SaaS Boost Version :**
  - **Workload OS  (Linux or Windows) :**

### Other

--- 

This is :bug: Bug Report

**Comment by brtrvn** [comment]
Fixed with merge of #150
