### ISSUE TITLE
API Gateway: Too Many Requests on environment update

### ISSUE THREAD

**Issue by aiavci** [awslabs/aws-saas-boost#167]
Updating an existing AWS SaaS Boost installation fails due to API throttling

### Reproduction Steps
1. Run `sh install.sh`
2. Select 4th option: Update existing AWS SaaS Boost deployment and enter the environment information

### What did you expect to happen?
AWS SaaS Boost services should update to latest version

### What actually happened?
Installation fails with API error

### Environment

  - **AWS Region  :**
  - **AWS SaaS Boost Version :*v1.1.1*
  - **Workload OS  (Linux or Windows) :**

### Other

`INFO  SaaSBoostInstall - Installation Error: Too Many Requests (Service: ApiGateway, Status Code: 429, Request ID: <Redacted>, Extended Request ID: null)
INFO  SaaSBoostInstall - Please see detailed log file saas-boost-install.log
ERROR SaaSBoostInstall - software.amazon.awssdk.services.apigateway.model.TooManyRequestsException: Too Many Requests (Service: ApiGateway, Status Code: 429, Request ID: <Redacted>, Extended Request ID: null)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleErrorResponse(CombinedResponseHandler.java:123)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleResponse(CombinedResponseHandler.java:79)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:59)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:40)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:40)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:30)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:73)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:42)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:78)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:40)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:50)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:36)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:81)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:36)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:56)
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:36)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.executeWithTimer(ApiCallTimeoutTrackingStage.java:80)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:60)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:42)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:48)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:31)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:37)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:26)
	at software.amazon.awssdk.core.internal.http.AmazonSyncHttpClient$RequestExecutionBuilderImpl.execute(AmazonSyncHttpClient.java:193)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.invoke(BaseSyncClientHandler.java:103)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.doExecute(BaseSyncClientHandler.java:167)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.lambda$execute$1(BaseSyncClientHandler.java:82)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.measureApiCallSuccess(BaseSyncClientHandler.java:175)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:76)
	at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:45)
	at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:56)
	at software.amazon.awssdk.services.apigateway.DefaultApiGatewayClient.createDeployment(DefaultApiGatewayClient.java:689)
	at software.amazon.awssdk.services.apigateway.ApiGatewayClient.createDeployment(ApiGatewayClient.java:682)
	at com.amazon.aws.partners.saasfactory.saasboost.SaaSBoostInstall.updateSaaSBoost(SaaSBoostInstall.java:446)
	at com.amazon.aws.partners.saasfactory.saasboost.SaaSBoostInstall.start(SaaSBoostInstall.java:203)
	at com.amazon.aws.partners.saasfactory.saasboost.SaaSBoostInstall.main(SaaSBoostInstall.java:150)`

--- 

This is :bug: Bug Report

**Comment by PoeppingT** [comment]
Hi @aiavci , thanks for creating this bug report! As I cannot reproduce this in my own environment, it would be helpful to get a speedy bugfix if you could provide the answers to a few questions:
1. Is this bug reproducible? That is to say, does this happen every time you try to run an update?
2. Do you have any local changes to your SaaS Boost environment that might be changing default behavior? In particular, are you changing the retry modes or retry policies for your AWS client?

This seems to be happening because
1. When an APIGateway stage is updated in CloudFormation it isn't redeployed, which means
2. In `updateSaaSBoost` in the installer, we need to redeploy both the public and private api stages (for the time being `updateSaaSBoost` updates the entire installation) using `createDeployment`, but
3. The service limit for `createDeployment` is only [1 request every 5 seconds](https://docs.aws.amazon.com/apigateway/latest/developerguide/limits.html)

**Comment by PoeppingT** [comment]
Hi @aiavci , thanks for submitting this bug report! I can reproduce this in my own environment and I am working towards a fix. Keep an eye on the PRs if you would like to review.
