### ISSUE TITLE
Deleting a SaaS Boost Environment with the Analytics module or an Active Directory install fails

### ISSUE THREAD

**Issue by PoeppingT** [awslabs/aws-saas-boost#185]
When creating a SaaS Boost Environment using the install script `install.sh` the installer will create three different parameters:
```
"/saas-boost/" + this.envName + "/ACTIVE_DIRECTORY_PASSWORD",
"/saas-boost/" + this.envName + "/METRICS_ANALYTICS_DEPLOYED",
"/saas-boost/" + this.envName + "/REDSHIFT_MASTER_PASSWORD"
```
Those same three parameters are deleted when deleting a SaaS Boost Environment using the install script `install.sh`.

However, those parameters are deleted before deleting the related CloudFormation stacks, which will cause stack delete failures when trying to delete the SaaS Boost Environment. Subsequent attempts to delete the environment using the installer will fail because those SSM parameters no longer exist, forcing the user to delete the stacks and all related AWS resources through the AWS console or some other method: not a small task.

### Reproduction Steps

Create a new SaaS Boost Environment using the installer. Install SaaS Boost Metrics + Analytics as part of the installation process.
Once the installation is complete, attempt to delete the SaaS Boost environment. It will fail.
Trying to delete again will also fail, but this time because the SSM parameters are deleted.

### What did you expect to happen?

The installer should successfully delete the SaaS Boost environment.

### What actually happened?

The installer was unable to successfully delete the SaaS Boost environment.

### Environment

  - **AWS Region  :**us-west-2
  - **AWS SaaS Boost Version :**v1.1.2
  - **Workload OS  (Linux or Windows) :**(no workload)

#### First stack delete failure(s):
```
RedshiftCluster DELETE_FAILED Parameters: [ssm-secure:/saas-boost/ui/REDSHIFT_MASTER_PASSWORD] cannot be found.
MetricsStream DELETE_FAILED Parameters: [ssm-secure:/saas-boost/ui/REDSHIFT_MASTER_PASSWORD:1] cannot be found.
```

#### Second installer failure:
```
2022-01-13 13:46:54.385  ERROR SaaSBoostInstall - software.amazon.awssdk.services.ssm.model.ParameterNotFoundException: null (Service: Ssm, Status Code: 400, Request ID: 57f093c5-0619-4abe-8fbd-e12e0b9e495f, Extended Request ID: null)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleErrorResponse(CombinedResponseHandler.java:123)
...
	at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:45)
	at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:56)
	at software.amazon.awssdk.services.ssm.DefaultSsmClient.getParameter(DefaultSsmClient.java:8598)
	at software.amazon.awssdk.services.ssm.SsmClient.getParameter(SsmClient.java:14737)
	at com.amazon.aws.partners.saasfactory.saasboost.SaaSBoostInstall.getExistingSaaSBoostAnalyticsDeployed(SaaSBoostInstall.java:1339)
	at com.amazon.aws.partners.saasfactory.saasboost.SaaSBoostInstall.loadExistingSaaSBoostEnvironment(SaaSBoostInstall.java:1218)
	at com.amazon.aws.partners.saasfactory.saasboost.SaaSBoostInstall.start(SaaSBoostInstall.java:191)
	at com.amazon.aws.partners.saasfactory.saasboost.SaaSBoostInstall.main(SaaSBoostInstall.java:150)
```
Originating from this code:
```
    protected boolean getExistingSaaSBoostAnalyticsDeployed() {
        LOGGER.info("Getting existing SaaS Boost Analytics module deployed from Parameter Store");
        boolean analyticsDeployed = false;
        if (isBlank(this.envName)) {
            this.envName = getExistingSaaSBoostEnvironment();
        }
        try {
            GetParameterResponse response = ssm.getParameter(request -> request
                    .name("/saas-boost/" + this.envName + "/METRICS_ANALYTICS_DEPLOYED")
            );
            analyticsDeployed = Boolean.parseBoolean(response.parameter().value());
        } catch (SdkServiceException ssmError) {
            // TODO CloudFormation should own this parameter, not the installer... it's possible the parameter doesn't exist
            // parameter not found is an exception
            if (!ssmError.getMessage().contains("not found")) {
                LOGGER.error("ssm:GetParameter error {}", ssmError.getMessage());
                LOGGER.error(getFullStackTrace(ssmError));
                throw ssmError;
            }
        }
        LOGGER.info("Loaded analytics deployed {}", analyticsDeployed);
        return analyticsDeployed;
    }
```

--- 

This is :bug: Bug Report

**Comment by PoeppingT** [comment]
Testing a fix for this now where we simply delete the SSM parameters after deleting the CloudFormation stacks. This bug gives us another good reason to develop a strong CI story for SaaS Boost: we want new users to be able to quickly and easily follow our onboarding steps, with bugs like this slowing down experimentation.

If you see this issue and you want to help out, feel free to submit discussions or issues recommending your ideas. Our current milestone tracking Boost CI/CD tasks is [here](https://github.com/awslabs/aws-saas-boost/milestone/1).
