### ISSUE TITLE
Saas Boost fails to build React Web application

### ISSUE THREAD

**Issue by MG-Charlotte** [awslabs/aws-saas-boost#22]
### The Question ###
Are there initial configuration steps required to enable a successful build of the Saas Boost React Web Application?

After running sh install.sh the install process beings and runs seemingly successfully until it reaches the "Start build of AWS Saas Boost React web application with yarn...".  Immediately an installation error is thrown.

I have verified that the prerequisites are installed and configured.
Here is the input provided when initiating sh install.sh

Launch Java Installer for SaaS Boost
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
Setting version to v0 as it is missing from the git properties file.

Welcome to the AWS SaaS Boost Installer
Setting version to v0 as it is missing from the git properties file.
Installer Version: 85459a1-dirty, Commit time: 2021-05-13T20:03:38-0400
Checking maven, yarn and AWS CLI...
Environment Checks for maven, yarn, and AWS CLI PASSED.

After the initial error, I ran the install script and chose the delete option to remove the installation.  I then verified via the AWS CloudFormation console that all components had been removed.  Just to be sure I was using the latest files, I deleted the Saas Boost folder and re-cloned the repo, and attempted to install again.  

The stack trace (below) seems to be pointing to a null value for the React App environment variables.  Should I use the output from CloudFormation (Cognito & API Gateway) in the client/web env file and re-run install using the update option?
### Environment ###

  - **AWS SaaS Boost Version:** 
1.89.0 (build df7253c)

### Other information ###

Here is the input provided when initiating sh install.sh

Launch Java Installer for SaaS Boost
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
Setting version to v0 as it is missing from the git properties file.

Welcome to the AWS SaaS Boost Installer
Setting version to v0 as it is missing from the git properties file.
Installer Version: 85459a1-dirty, Commit time: 2021-05-13T20:03:38-0400
Checking maven, yarn and AWS CLI...
Environment Checks for maven, yarn, and AWS CLI PASSED.

Would you like to continue the installation with the following options?
AWS SaaS Boost Environment Name: dev
Admin Email Address: <private_email>.io
Route 53 Domain for AWS SaaS Boost environment: portal.<mydomain>.io
Install Metrics and Analytics: y
Amazon Quicksight user for setup of Metrics and Analytics: n/a
Setup Active Directory for FSX for Windows: n
Enter y to continue or n to cancel: y
Continuing installation of AWS SaaS Boost

Stack Trace:

Awaiting CloudFormation Stack sb-dev to complete.  Sleep 5 minute(s)...
Awaiting CloudFormation Stack sb-dev to complete.  Sleep 1 minute(s)...
Awaiting CloudFormation Stack sb-dev to complete.  Sleep 1 minute(s)...
Awaiting CloudFormation Stack sb-dev to complete.  Sleep 1 minute(s)...
Awaiting CloudFormation Stack sb-dev to complete.  Sleep 1 minute(s)...
Awaiting CloudFormation Stack sb-dev to complete.  Sleep 1 minute(s)...
Awaiting CloudFormation Stack sb-dev to complete.  Sleep 1 minute(s)...
Awaiting CloudFormation Stack sb-dev to complete.  Sleep 1 minute(s)...
Awaiting CloudFormation Stack sb-dev to complete.  Sleep 1 minute(s)...
Awaiting CloudFormation Stack sb-dev to complete.  Sleep 1 minute(s)...
CloudFormation Stack: sb-dev completed successfully.
Copy files to S3 web site bucket
Start build of AWS SaaS Boost React web application with yarn ...

Installation Error: null
Please see detailed log file saas-boost-install.log
java.lang.NullPointerException
	at java.base/java.lang.ProcessEnvironment.validateValue(ProcessEnvironment.java:120)
	at java.base/java.lang.ProcessEnvironment$Value.valueOf(ProcessEnvironment.java:203)
	at java.base/java.lang.ProcessEnvironment$StringEnvironment.put(ProcessEnvironment.java:243)
	at java.base/java.lang.ProcessEnvironment$StringEnvironment.put(ProcessEnvironment.java:221)
	at com.amazon.aws.partners.saasfactory.saasboost.SaaSBoostInstall.buildAndCopyWebApp(SaaSBoostInstall.java:2257)
	at com.amazon.aws.partners.saasfactory.saasboost.SaaSBoostInstall.installSaaSBoost(SaaSBoostInstall.java:1459)
	at com.amazon.aws.partners.saasfactory.saasboost.SaaSBoostInstall.start(SaaSBoostInstall.java:977)
	at com.amazon.aws.partners.saasfactory.saasboost.SaaSBoostInstall.main(SaaSBoostInstall.java:198)

**When I open up the saas-boost-install.log, here are the details showing the error.**

2021-05-14 16:19:23 SaaSBoostInstall.createSaaSBoostStack createSaaSBoostStack::stack id arn:aws:cloudformation:us-east-1:045258344123:stack/sb-dev/abca1e00-b4f1-11eb-83c6-0a8858a4ea55
2021-05-14 16:19:23 SaaSBoostInstall.outputMessage Awaiting CloudFormation Stack sb-dev to complete.  Sleep 5 minute(s)...
2021-05-14 16:24:24 SaaSBoostInstall.outputMessage Awaiting CloudFormation Stack sb-dev to complete.  Sleep 1 minute(s)...
2021-05-14 16:25:24 SaaSBoostInstall.outputMessage Awaiting CloudFormation Stack sb-dev to complete.  Sleep 1 minute(s)...
2021-05-14 16:26:25 SaaSBoostInstall.outputMessage Awaiting CloudFormation Stack sb-dev to complete.  Sleep 1 minute(s)...
2021-05-14 16:27:26 SaaSBoostInstall.outputMessage Awaiting CloudFormation Stack sb-dev to complete.  Sleep 1 minute(s)...
2021-05-14 16:28:27 SaaSBoostInstall.outputMessage Awaiting CloudFormation Stack sb-dev to complete.  Sleep 1 minute(s)...
2021-05-14 16:29:27 SaaSBoostInstall.outputMessage Awaiting CloudFormation Stack sb-dev to complete.  Sleep 1 minute(s)...
2021-05-14 16:30:28 SaaSBoostInstall.outputMessage Awaiting CloudFormation Stack sb-dev to complete.  Sleep 1 minute(s)...
2021-05-14 16:31:29 SaaSBoostInstall.outputMessage Awaiting CloudFormation Stack sb-dev to complete.  Sleep 1 minute(s)...
2021-05-14 16:32:31 SaaSBoostInstall.outputMessage Awaiting CloudFormation Stack sb-dev to complete.  Sleep 1 minute(s)...
2021-05-14 16:33:31 SaaSBoostInstall.outputMessage CloudFormation Stack: sb-dev completed successfully.
2021-05-14 16:33:31 SaaSBoostInstall.outputMessage Copy files to S3 web site bucket
2021-05-14 16:33:32 SaaSBoostInstall.outputMessage Start build of AWS SaaS Boost React web application with yarn ...
2021-05-14 16:33:32 SaaSBoostInstall.outputMessage ===========================================================
2021-05-14 16:33:32 SaaSBoostInstall.outputMessage Installation Error: null
2021-05-14 16:33:32 SaaSBoostInstall.outputMessage Please see detailed log file saas-boost-install.log
2021-05-14 16:33:32 SaaSBoostInstall.main java.lang.NullPointerException
        at java.base/java.lang.ProcessEnvironment.validateValue(ProcessEnvironment.java:120)
        at java.base/java.lang.ProcessEnvironment$Value.valueOf(ProcessEnvironment.java:203)
        at java.base/java.lang.ProcessEnvironment$StringEnvironment.put(ProcessEnvironment.java:243)
        at java.base/java.lang.ProcessEnvironment$StringEnvironment.put(ProcessEnvironment.java:221)
        at com.amazon.aws.partners.saasfactory.saasboost.SaaSBoostInstall.buildAndCopyWebApp(SaaSBoostInstall.java:2257)
        at com.amazon.aws.partners.saasfactory.saasboost.SaaSBoostInstall.installSaaSBoost(SaaSBoostInstall.java:1459)
        at com.amazon.aws.partners.saasfactory.saasboost.SaaSBoostInstall.start(SaaSBoostInstall.java:977)
        at com.amazon.aws.partners.saasfactory.saasboost.SaaSBoostInstall.main(SaaSBoostInstall.java:198)

2021-05-14 16:33:32 SaaSBoostInstall.outputMessage java.lang.NullPointerException
        at java.base/java.lang.ProcessEnvironment.validateValue(ProcessEnvironment.java:120)
        at java.base/java.lang.ProcessEnvironment$Value.valueOf(ProcessEnvironment.java:203)
        at java.base/java.lang.ProcessEnvironment$StringEnvironment.put(ProcessEnvironment.java:243)
        at java.base/java.lang.ProcessEnvironment$StringEnvironment.put(ProcessEnvironment.java:221)
        at com.amazon.aws.partners.saasfactory.saasboost.SaaSBoostInstall.buildAndCopyWebApp(SaaSBoostInstall.java:2257)
        at com.amazon.aws.partners.saasfactory.saasboost.SaaSBoostInstall.installSaaSBoost(SaaSBoostInstall.java:1459)
        at com.amazon.aws.partners.saasfactory.saasboost.SaaSBoostInstall.start(SaaSBoostInstall.java:977)
        at com.amazon.aws.partners.saasfactory.saasboost.SaaSBoostInstall.main(SaaSBoostInstall.java:198)

**Comment by hariohmprasath** [comment]
Hi,

Thanks for reporting the issue, can you please check the status of `sb-dev-web-xxxxx` cloudformation stack? 

### Just to provide some context:

The installer code is reading all the cloudformation exports of the above mentioned stack and storing it in a HashMap, specifically the ones starting with `saas-boost` prefix. Values in this HashMap later set as environment variables, since the value for export variable `saas-boost::dev-<<AWS_REGION>>:webUrl` is Null you end up getting this as `NullPointerException` on the `ProcessEnvironment` code.

**Code listing output and saving saas-boost prefix in HashMap**

```java
ListExportsResponse response = cfn.listExports(ListExportsRequest.builder().build());

Map<String, String> exportsMap = new HashMap<>();
for (Export export : response.exports()) {
    if (export.name().startsWith("saas-boost::" + envName)) {
        exportsMap.put(export.name(), export.value());
    }
}
```        

**Code causing NullPointerException due to Null value in `saas-boost::dev-<<AWS_REGION>>:webUrl` output variable**

```java
env.put("REACT_APP_SIGNOUT_URI",exportsMap.get(prefix + "webUrl"));
```

Two things to check in this case:

* What's the status of `sb-dev-web-xxxxx` cloudformation stack? 
* What's the value for `saas-boost::dev-<<AWS_REGION>>:webUrl` variable mentioned in the "Output" tab of the `sb-dev-web-xxxxx` cloudformation stack?

Along with this if you can share `saas-boost-install.log` file it will be easy to understand and troubleshoot this issue.

Thanks,
Hari

**Comment by mgwinthrop** [comment]
Thanks for the reply.

Here is the status of my sb-dev-web-xxxx and AWS_REGION
![Screen Shot 2021-05-15 at 3 54 27 PM](https://user-images.githubusercontent.com/448935/118376463-f92a8500-b595-11eb-82af-bd8b31b4c983.png)

**Comment by mgwinthrop** [comment]
Sorry, forgot to upload my log file...
[saas-boost-install.log](https://github.com/awslabs/aws-saas-boost/files/6488213/saas-boost-install.log)

**Comment by hariohmprasath** [comment]
Hi,
Appreciate all your responses in this. Based on some initial analysis, looks like the AWS resources are getting created in one AWS region and CFN client is trying to read them from the different/default region. 

Here is the description about the static method `CloudFormationClient.create()` which reads the exports from CFN:

```java
/** Create a {@link CloudFormationClient} with the region loaded from the
* {@link software.amazon.awssdk.regions.providers.DefaultAwsRegionProviderChain} and credentials loaded from the
* {@link software.amazon.awssdk.auth.credentials.DefaultCredentialsProvider}.
**/

this.cfn = CloudFormationClient.create();     
```

One quick test you can run from your end would be to just change the above code to:

```java
cfn = CloudFormationClient.builder().region(AWS_REGION).build();
```

On Line numbers 131 & 2231 in the file [SaaSBoostInstall.java](https://github.com/awslabs/aws-saas-boost/blob/main/installer/src/main/java/com/amazon/aws/partners/saasfactory/saasboost/SaaSBoostInstall.java) under `saas-boost/installer/src/main/java/com/amazon/aws/partners/saasfactory/saasboost` directory. Once done, set the right default aws region in env variable by running the following command:

```bash
export AWS_REGION=<<AWS_REGION>>
```

Run the install again:

```bash
sh install.sh
```

Since I am not able to recreate this in my end would need some help from you on this. If everything works fine, I can submit a pull request with these changes.

Thanks
Hari

**Comment by 4patelr** [comment]
Hi @mgwinthrop,

I agree with Hari that for some reason the installer is not reading the exported values from the CloudFormation stack. Like Hari, I am not able to reproduce this. What version of the AWS CLI are you using and what operating system are you running the installer from?

You can try what Hari suggested but can you please also add a LOGGER.info in the loop that reads the exports as follows?

```
        Map<String, String> exportsMap = new HashMap<>();
        for (Export export : response.exports()) {
            if (export.name().startsWith("saas-boost::" + envName)) {
                exportsMap.put(export.name(), export.value());
            }
            LOGGER.info("Export name: {}, Export value: {}", export.name(), export.value());
        }
```

**Comment by mgwinthrop** [comment]
Hi @4patelr,

AWS CLI version = aws-cli/2.2.4 Python/3.8.8 Darwin/19.6.0 exe/x86_64 prompt/off
OS/OS version = Mac OSX 10.15.7

I am still getting the same failure after making the changes recommended by @hariohmprasath.  I will add the Logger statement and post my logs and outputs after a little sleep.

**Comment by mgwinthrop** [comment]
@hariohmprasath & @4patelr,

I was able to successfully install the app on a different AWS account that I have.  I used the following steps:
1. Updated my default AWS CLI profile to use the different AWS account
2. Change the following code from ` this.cfn = CloudFormationClient.create();` to `cfn = CloudFormationClient.builder().region(AWS_REGION).build();`
3. Ran sh install.sh without any errors

Then, still using the new AWS Account
1. I reverted the SaaSBoostInstall.java code back to ` this.cfn = CloudFormationClient.create();` 
2. Ran sh install.sh and created a new environment
3. Install ran without issues

So I think this is a "It's not you, it's me" situation.  I will try using a different IAM account in the original AWS account and see if that makes a difference.

**Comment by 4patelr** [comment]
Hi @mgwinthrop,

That is great news you got it installed. I don't think it is a case of "it's me" situation. Do you know if the AWS Account where you encountered the errors has more than 500 CloudFormation exports? 

I noticed the installer is not using the nextToken to fetch all of the exports and perhaps this is causing the issue. If you still have the stack in this account, could you update the installer with the following code in the buildAndCopyWebApp method and then execute install.sh and choose option 3 to update the Web .

From line 2230:
```
        //refresh the client
        cfn = CloudFormationClient.create();

        String nextToken = null;
        Map<String, String> exportsMap = new HashMap<>();
        do {
            ListExportsResponse response = cfn.listExports(ListExportsRequest.builder()
                    .nextToken(nextToken)
                    .build());
            nextToken = response.nextToken();
            for (Export export : response.exports()) {
                if (export.name().startsWith("saas-boost::" + envName)) {
                    exportsMap.put(export.name(), export.value());
                }
                LOGGER.info("Export name: {}, Export value: {}", export.name(), export.value());
            }
        } while (null != nextToken);
```

**Comment by mgwinthrop** [comment]
Yes, the original AWS account does have more than 500 exports.  

So, I just update the code to use the token as provided.  And I am now able to install, login, and configure SaaS Boost in my original AWS account using the same IAM account.  

Thank you!

**Comment by hariohmprasath** [comment]
This is outstanding. Thanks @mgwinthrop for patiently responding to all the suggestions. @4patelr superb job by the way in identifying the issue. I noticed another place in code where we can do a similar change along with region changes. I have made the required changes and sent in a pull request, feel review to review it. Thanks.
