### ISSUE TITLE
During install the InvokeClearWebsiteBucket custom resource fails to create

### ISSUE THREAD

**Issue by terrylimnsv** [awslabs/aws-saas-boost#273]
I am trying to deploy a new installation but the install.sh script failed.

The CloudFormation error for the InvokeClearWebsiteBucket custom resource:

`CloudFormation did not receive a response from your Custom Resource. Please check your logs for requestId [aed836fa-a458-4b84-97de-f6b7243fe992]. If you are using the Python cfn-response module, you may need to update your Lambda function code so that CloudFormation can attach the updated version.`

### Reproduction Steps

I followed the instructions for installing from Cloud9.

### What did you expect to happen?

The installation would complete without errors.

### What actually happened?

The installation failed.

### Environment

  - **AWS Region  : us-east-1**
  - **AWS SaaS Boost Version : Installer Version 9793e06 **
  - **Workload OS  (Linux or Windows) : NA**

### Other

--- 

This is :bug: Bug Report

**Comment by brtrvn** [comment]
Thanks for the bug report @terrylimnsv 
Can you look at the CloudWatch Log Group for `/aws/lambda/sb-${SAAS_BOOST_ENVIRONMENT}-clear-bucket` and see if there are more details about the failure?
We've been noticing more HTTP timeouts when putting responses back to the CloudFormation S3 bucket. Working on some changes to the custom resources so they retry the HTTP PUT if it fails the first time.

**Comment by terrylimnsv** [comment]
I found these entries in the log:

`2022-08-10 16:45:11.021  ERROR CloudFormationResponse - Failed to complete HTTP request`

`2022-08-10 16:45:11.023  ERROR CloudFormationResponse - java.io.IOException: HTTP/1.1 header parser received no bytes
	at java.net.http/jdk.internal.net.http.HttpClientImpl.send(Unknown Source)
	at java.net.http/jdk.internal.net.http.HttpClientFacade.send(Unknown Source)
	at com.amazon.aws.partners.saasfactory.saasboost.CloudFormationResponse.send(CloudFormationResponse.java:57)
	at com.amazon.aws.partners.saasfactory.saasboost.CloudFormationResponse.send(CloudFormationResponse.java:42)
	at com.amazon.aws.partners.saasfactory.saasboost.ClearS3Bucket.lambda$handleRequest$4(ClearS3Bucket.java:56)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: HTTP/1.1 header parser received no bytes
	at java.net.http/jdk.internal.net.http.common.Utils.wrapWithExtraDetail(Unknown Source)
	at java.net.http/jdk.internal.net.http.Http1Response$HeadersReader.onReadError(Unknown Source)
	at java.net.http/jdk.internal.net.http.Http1AsyncReceiver.checkForErrors(Unknown Source)
	at java.net.http/jdk.internal.net.http.Http1AsyncReceiver.flush(Unknown Source)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SynchronizedRestartableTask.run(Unknown Source)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(Unknown Source)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(Unknown Source)
	at java.net.http/jdk.internal.net.http.HttpClientImpl$DelegatingExecutor.execute(Unknown Source)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(Unknown Source)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(Unknown Source)
	at java.net.http/jdk.internal.net.http.Http1AsyncReceiver.onReadError(Unknown Source)
	at java.net.http/jdk.internal.net.http.Http1AsyncReceiver$Http1TubeSubscriber.onComplete(Unknown Source)
	at java.net.http/jdk.internal.net.http.common.SSLTube$DelegateWrapper.onComplete(Unknown Source)
	at java.net.http/jdk.internal.net.http.common.SSLTube$SSLSubscriberWrapper.complete(Unknown Source)
	at java.net.http/jdk.internal.net.http.common.SSLTube$SSLSubscriberWrapper.onNewSubscription(Unknown Source)
	at java.net.http/jdk.internal.net.http.common.SSLTube$SSLSubscriberWrapper.processPendingSubscriber(Unknown Source)
	at java.net.http/jdk.internal.net.http.common.SSLTube$SSLSubscriberWrapper.setDelegate(Unknown Source)
	at java.net.http/jdk.internal.net.http.common.SSLTube.connectFlows(Unknown Source)
	at java.net.http/jdk.internal.net.http.Http1Exchange.connectFlows(Unknown Source)
	at java.net.http/jdk.internal.net.http.Http1Exchange.lambda$sendHeadersAsync$4(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.thenCompose(Unknown Source)
	at java.net.http/jdk.internal.net.http.Http1Exchange.sendHeadersAsync(Unknown Source)
	at java.net.http/jdk.internal.net.http.Exchange.lambda$responseAsyncImpl0$8(Unknown Source)
	at java.net.http/jdk.internal.net.http.Exchange.checkFor407(Unknown Source)
	at java.net.http/jdk.internal.net.http.Exchange.lambda$responseAsyncImpl0$9(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.uniHandleStage(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.handle(Unknown Source)
	at java.net.http/jdk.internal.net.http.Exchange.responseAsyncImpl0(Unknown Source)
	at java.net.http/jdk.internal.net.http.Exchange.responseAsyncImpl(Unknown Source)
	at java.net.http/jdk.internal.net.http.Exchange.responseAsync(Unknown Source)
	at java.net.http/jdk.internal.net.http.MultiExchange.responseAsyncImpl(Unknown Source)
	at java.net.http/jdk.internal.net.http.MultiExchange.lambda$responseAsync0$2(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
	at java.net.http/jdk.internal.net.http.HttpClientImpl$DelegatingExecutor.execute(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeAsync(Unknown Source)
	at java.net.http/jdk.internal.net.http.MultiExchange.responseAsync(Unknown Source)
	at java.net.http/jdk.internal.net.http.HttpClientImpl.sendAsync(Unknown Source)
	... 10 more
Caused by: java.io.EOFException: EOF reached while reading
	... 40 more

`

How do I recover from this?

**Comment by brtrvn** [comment]
Yep - there was a problem with the HTTP PUT to the CloudFormation S3 bucket for the custom resource response. Pull the latest from HEAD of the main branch and reinstall SaaS Boost. Let us know if you experience the error in the future.

**Comment by terrylimnsv** [comment]
> Yep - there was a problem with the HTTP PUT to the CloudFormation S3 bucket for the custom resource response. Pull the latest from HEAD of the main branch and reinstall SaaS Boost. Let us know if you experience the error in the future.

After pulling the update I ran the install script and tried both options 5 (delete) and 4 (update). Both gave the following error:

`Missing required CloudFormation stack output PublicSubnet1 from stack sb-dev`

What is the cleanest way to reinstall Saas Boost? Do I just delete the CloudFormation stack and then option 1 (new install)?
