### ISSUE TITLE
During fresh install, `CloudFormationException: The security token included in the request is expired`

### ISSUE THREAD

**Issue by cfregly** [awslabs/aws-saas-boost#295]
```
ERROR SaaSBoostInstall - cloudformation error
software.amazon.awssdk.services.cloudformation.model.CloudFormationException: The security token included in the request is expired
```

### Reproduction Steps

./install.sh <= new install

### What did you expect to happen?

no errors

### What actually happened?

errors with installer and this AccessDenied on admin web app thru CloudFront:

<img width="769" alt="image" src="https://user-images.githubusercontent.com/1438064/191076615-fc580cb0-e0f0-4c48-810a-1191ba061329.png">

### Environment

  - **us-east-1**
  - **[AWS SaaS Boost Version ](https://github.com/awslabs/aws-saas-boost/commit/ebe713c966c7632285b93415b8e2bbde2fb14956)**
  - **Linus**

### Other
```
2022-09-18 21:48:51.801  INFO  SaaSBoostInstall - Uploading Lambda source package to S3 metering-billing/lambdas/target/BillingService-lambda.zip -> lambdas/BillingService-lambda.zip
2022-09-18 21:48:51.801  DEBUG SaaSBoostArtifactsBucket - Putting metering-billing/lambdas/target/BillingService-lambda.zip to Artifacts bucket: sb-trueprod-artifacts-766hk4h3a3xd
2022-09-18 21:48:51.937  INFO  SaaSBoostInstall - Running CloudFormation
2022-09-18 21:49:44.868  DEBUG SaaSBoostInstall - Could not find any ApplicationServicesMacro resource
2022-09-18 21:49:44.868  INFO  SaaSBoostInstall - createSaaSBoostStack::create stack sb-trueprod
2022-09-18 21:49:45.369  INFO  SaaSBoostInstall - createSaaSBoostStack::stack id arn:aws:cloudformation:us-east-1:079002598131:stack/sb-trueprod/ceed4c30-379b-11ed-bcfa-0a38fdf064f9
2022-09-18 21:49:45.452  INFO  SaaSBoostInstall - Awaiting CloudFormation Stack sb-trueprod to complete.  Sleep 5 minute(s)...
2022-09-18 21:54:45.535  INFO  SaaSBoostInstall - Awaiting CloudFormation Stack sb-trueprod to complete.  Sleep 1 minute(s)...
2022-09-18 21:55:45.610  INFO  SaaSBoostInstall - Awaiting CloudFormation Stack sb-trueprod to complete.  Sleep 1 minute(s)...
2022-09-18 21:56:45.685  INFO  SaaSBoostInstall - Awaiting CloudFormation Stack sb-trueprod to complete.  Sleep 1 minute(s)...
2022-09-18 21:57:45.777  INFO  SaaSBoostInstall - Awaiting CloudFormation Stack sb-trueprod to complete.  Sleep 1 minute(s)...
2022-09-18 21:58:45.796  ERROR SaaSBoostInstall - cloudformation error
software.amazon.awssdk.services.cloudformation.model.CloudFormationException: The security token included in the request is expired (Service: CloudFormation, Status Code: 403, Request ID: deedd7e0-e4f9-4927-a18d-6d4447a30bf6)
        at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleErrorResponse(CombinedResponseHandler.java:125) ~[SaaSBoostInstall-1.0.0-shaded.jar:?]
        at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleResponse(CombinedResponseHandler.java:82) ~[SaaSBoostInstall-1.0.0-shaded.jar:?]
        at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:60) ~[SaaSBoostInstall-1.0.0-shaded.jar:?]
        at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:41) ~[SaaSBoostInstall-1.0.0-shaded.jar:?]
        at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:40) ~[SaaSBoostInstall-1.0.0-shaded.jar:?]
        at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:30) ~[SaaSBoostInstall-1.0.0-shaded.jar:?]
        at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206) ~[SaaSBoostInstall-1.0.0-shaded.jar:?]
        at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:73) ~[SaaSBoostInstall-1.0.0-shaded.jar:?]
        at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:42) ~[SaaSBoostInstall-1.0.0-shaded.jar:?]
        at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:78) ~[SaaSBoostInstall-1.0.0-shaded.jar:?]
        at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:40) ~[SaaSBoostInstall-1.0.0-shaded.jar:?]
        at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:50) ~[SaaSBoostInstall-1.0.0-shaded.jar:?]
        at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:36) ~[SaaSBoostInstall-1.0.0-shaded.jar:?]
        at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:81) ~[SaaSBoostInstall-1.0.0-shaded.jar:?]
        at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:36) ~[SaaSBoostInstall-1.0.0-shaded.jar:?]
        at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206) ~[SaaSBoostInstall-1.0.0-shaded.jar:?]
        at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:56) ~[SaaSBoostInstall-1.0.0-shaded.jar:?]
        at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:36) ~[SaaSBoostInstall-1.0.0-shaded.jar:?]
        at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.executeWithTimer(ApiCallTimeoutTrackingStage.java:80) ~[SaaSBoostInstall-1.0.0-shaded.jar:?]
        at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:60) ~[SaaSBoostInstall-1.0.0-shaded.jar:?]
        at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:42) ~[SaaSBoostInstall-1.0.0-shaded.jar:?]
        at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:48) ~[SaaSBoostInstall-1.0.0-shaded.jar:?]
        at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:31) ~[SaaSBoostInstall-1.0.0-shaded.jar:?]
        at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206) ~[SaaSBoostInstall-1.0.0-shaded.jar:?]
        at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206) ~[SaaSBoostInstall-1.0.0-shaded.jar:?]
        at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:37) ~[SaaSBoostInstall-1.0.0-shaded.jar:?]
        at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:26) ~[SaaSBoostInstall-1.0.0-shaded.jar:?]
        at software.amazon.awssdk.core.internal.http.AmazonSyncHttpClient$RequestExecutionBuilderImpl.execute(AmazonSyncHttpClient.java:193) ~[SaaSBoostInstall-1.0.0-shaded.jar:?]
        at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.invoke(BaseSyncClientHandler.java:103) ~[SaaSBoostInstall-1.0.0-shaded.jar:?]
        at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.doExecute(BaseSyncClientHandler.java:167) ~[SaaSBoostInstall-1.0.0-shaded.jar:?]
        at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.lambda$execute$1(BaseSyncClientHandler.java:82) ~[SaaSBoostInstall-1.0.0-shaded.jar:?]
        at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.measureApiCallSuccess(BaseSyncClientHandler.java:175) ~[SaaSBoostInstall-1.0.0-shaded.jar:?]
        at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:76) ~[SaaSBoostInstall-1.0.0-shaded.jar:?]
        at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:45) ~[SaaSBoostInstall-1.0.0-shaded.jar:?]
        at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:56) ~[SaaSBoostInstall-1.0.0-shaded.jar:?]
        at software.amazon.awssdk.services.cloudformation.DefaultCloudFormationClient.describeStacks(DefaultCloudFormationClient.java:2079) ~[SaaSBoostInstall-1.0.0-shaded.jar:?]
        at software.amazon.awssdk.services.cloudformation.CloudFormationClient.describeStacks(CloudFormationClient.java:2998) ~[SaaSBoostInstall-1.0.0-shaded.jar:?]
        at com.amazon.aws.partners.saasfactory.saasboost.SaaSBoostInstall.createSaaSBoostStack(SaaSBoostInstall.java:1361) [SaaSBoostInstall-1.0.0-shaded.jar:?]
        at com.amazon.aws.partners.saasfactory.saasboost.SaaSBoostInstall.installSaaSBoost(SaaSBoostInstall.java:407) [SaaSBoostInstall-1.0.0-shaded.jar:?]
        at com.amazon.aws.partners.saasfactory.saasboost.SaaSBoostInstall.start(SaaSBoostInstall.java:228) [SaaSBoostInstall-1.0.0-shaded.jar:?]
        at com.amazon.aws.partners.saasfactory.saasboost.SaaSBoostInstall.main(SaaSBoostInstall.java:176) [SaaSBoostInstall-1.0.0-shaded.jar:?]
2022-09-18 21:58:45.800  ERROR SaaSBoostInstall - software.amazon.awssdk.services.cloudformation.model.CloudFormationException: The security token included in the request is expired (Service: CloudFormation, Status Code: 403, Request ID: deedd7e0-e4f9-4927-a18d-6d4447a30bf6)
```

--- 

This is :bug: Bug Report

**Comment by cfregly** [comment]
I did 4/ and 3/ (in that order) and it works now:
3. Update Web Application for existing AWS SaaS Boost deployment.
4. Update existing AWS SaaS Boost deployment.

**Comment by cfregly** [comment]
sounds like just 3/ would have worked since the upload of the react app to s3 happens after couldformation comes back to say it’s done - and the while loop of the describe stack (to determine if cfn is done) is failing on a timeout.

**Comment by PoeppingT** [comment]
Hi @cfregly , can you provide more information on how I can reproduce this issue? The same process you've provided does not lead to any errors on my own personal computer. Did you download a fresh clone of `main`, or were you using some version?

**Comment by brtrvn** [comment]
Sounds like this was experience while running the installer in a Cloud9 instance. Had any manual changes been effected against the Cloud9 instance credentials or was this a freshly created Cloud9 instance just for the purpose of installing SaaS Boost with the default setup?

**Comment by PoeppingT** [comment]
Closing as there is no adequate reproduction steps for this task. @cfregly , if you end up seeing this again, please come back to reopen this and post the steps you took to reproduce the error.
