### ISSUE TITLE
Disabling a tenant does not work

### ISSUE THREAD

**Issue by aspcanada** [awslabs/aws-saas-boost#44]
There seems to be a bug in the tenant-enable-disable lambda function. When I review the logs I get an exception (see below). 

### Reproduction Steps

From the admin page, select a tenant and disable them.

### What did you expect to happen?

Status is set to active, but the ALB does not respond with the disabled page.

### What actually happened?

The tenant's page continues to be served up by the LB. Is should be serving up a disabled page

### Environment

  - **AWS Region  :**us-west-2
  - **AWS SaaS Boost Version :**v0
  - **Workload OS  (Linux or Windows) :**Linux

### Other

class java.lang.Boolean cannot be cast to class java.lang.String (java.lang.Boolean and java.lang.String are in module java.base of loader 'bootstrap'): java.lang.ClassCastException
java.lang.ClassCastException: class java.lang.Boolean cannot be cast to class java.lang.String (java.lang.Boolean and java.lang.String are in module java.base of loader 'bootstrap')
	at com.amazon.aws.partners.saasfactory.saasboost.AlbSetListenerRule.handleRequest(AlbSetListenerRule.java:59)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)

--- 

This is :bug: Bug Report

**Comment by aspcanada** [comment]
Looks like you are missing the closing `>` for the html tag here:

https://github.com/awslabs/aws-saas-boost/blob/2c1e4a0046234d2a0ecd3ed46e1257084d132248/functions/alb-update/src/main/java/com/amazon/aws/partners/saasfactory/saasboost/AlbSetListenerRule.java#L82

**Comment by aspcanada** [comment]
I also updated the boolean check (`if (status) {`) here: 

https://github.com/awslabs/aws-saas-boost/blob/2c1e4a0046234d2a0ecd3ed46e1257084d132248/functions/alb-update/src/main/java/com/amazon/aws/partners/saasfactory/saasboost/AlbSetListenerRule.java#L78

But now I am getting a different exception:
`METRIC_PUBLISHERS: java.lang.NoSuchFieldError
java.lang.NoSuchFieldError: METRIC_PUBLISHERS
	at software.amazon.awssdk.services.sts.DefaultStsClient.resolveMetricPublishers(DefaultStsClient.java:1274)
	at software.amazon.awssdk.services.sts.DefaultStsClient.assumeRole(DefaultStsClient.java:279)
	at software.amazon.awssdk.services.sts.StsClient.assumeRole(StsClient.java:440)
	at com.amazon.aws.partners.saasfactory.saasboost.ApiGatewayHelper.getTemporaryCredentials(ApiGatewayHelper.java:160)
	at com.amazon.aws.partners.saasfactory.saasboost.ApiGatewayHelper.signApiRequest(ApiGatewayHelper.java:146)
	at com.amazon.aws.partners.saasfactory.saasboost.ApiGatewayHelper.signAndExecuteApiRequest(ApiGatewayHelper.java:63)
	at com.amazon.aws.partners.saasfactory.saasboost.AlbSetListenerRule.getAlbId(AlbSetListenerRule.java:136)
	at com.amazon.aws.partners.saasfactory.saasboost.AlbSetListenerRule.handleRequest(AlbSetListenerRule.java:64)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) `

**Comment by 4patelr** [comment]
I am testing a fix as well had the same error with the METRIC_PUBLISHERS and resolved it by updating dependency in the pom.xml to 2.14.26 to match the versions used in the ApiGatewayHelper.

```
       <dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>elasticloadbalancingv2</artifactId>
            <version>2.14.26</version>
```

I also modified the update_service.sh in the alb-update folder to correct the name of the Lambda function to "sb-${ENVIRONMENT}-tenant-enable-disable". 

However, even after this fix, i noticed that since only the default rule is setup on the ALB the update from the Lambda fails. I am testing to put another rule in place and set priority as 1. This is in the tenant-onboarding.yaml. Once I have it working I will push a fix.

**Comment by 4patelr** [comment]
Fix has been pushed including update to tenant-onboarding.yaml. You will need to delete your existing tenants and then use the installer to update the AWS SaaS Boost environment. Thereafter, you can provision a new tenant and the tenant enable and disable should work.
