### ISSUE TITLE
When onboarding tenant, got No value exception

### ISSUE THREAD

**Issue by bella-kwon** [awslabs/aws-saas-boost#466]
### Reproduction Step
dev: Cloud9
1. install saas-boost without metric/directory service
2. push app (just nginx)
3. provision tenant through boost web page.

### What did you expect to happen?

Tenant created properly and showed on tenants menu.

### What actually happened?

CloudWatch log as follows.

```
No value present: java.util.NoSuchElementException
java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.get(Unknown Source)
	at com.amazon.aws.partners.saasfactory.saasboost.ApiGatewayHelper.executeApiRequest(ApiGatewayHelper.java:103)
	at com.amazon.aws.partners.saasfactory.saasboost.ApiGatewayHelper.signAndExecuteApiRequest(ApiGatewayHelper.java:88)
	at com.amazon.aws.partners.saasfactory.saasboost.OnboardingService.getSetting(OnboardingService.java:2196)
	at com.amazon.aws.partners.saasfactory.saasboost.OnboardingService.handleOnboardingBaseProvisioned(OnboardingService.java:1034)
	at com.amazon.aws.partners.saasfactory.saasboost.OnboardingService.handleOnboardingEvent(OnboardingService.java:362)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
```

### Environment

  - **AWS Region  : ap-northeast-2**
  - **AWS SaaS Boost Version : v2.1.0**
  - **Workload OS  (Linux or Windows) : Linux**

### Other

Since I got the NoValue exception, I just checked s3, filesysten, database. I finally got success in onboarding process.

--- 

This is :bug: Bug Report

**Comment by raman231** [comment]
+1
Getting same error while onboarding tenant.

Error occurs when calling OnboardingService - Calling settings service to fetch setting TENANT_STORAGE_BUCKET and such parameter does not exist in parameter store
