### ISSUE TITLE
Validating status does not change after Onboarding is created.

### ISSUE THREAD

**Issue by YutaOkoshi** [awslabs/aws-saas-boost#540]
I looked at the "/aws/lambda/sb-isen-onboarding-validation" log and found that the processValidateOnboardingQueue is occurring.

![スクリーンショット 2023-12-18 15 32 34](https://github.com/awslabs/aws-saas-boost/assets/37532269/86ac399f-31c0-472e-9f7d-c0469a815571)

Probably this is the reason why it does not change from Onboarding status.

/aws/lambda/sb-isen-onboarding-validation
```
begin 0, end -2, length 29: java.lang.StringIndexOutOfBoundsException
java.lang.StringIndexOutOfBoundsException: begin 0, end -2, length 29
	at java.base/java.lang.String.checkBoundsBeginEnd(Unknown Source)
	at java.base/java.lang.String.substring(Unknown Source)
	at com.amazon.aws.partners.saasfactory.saasboost.OnboardingService.processValidateOnboardingQueue(OnboardingService.java:1260)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)

begin 0, end -2, length 29: java.lang.StringIndexOutOfBoundsException java.lang.StringIndexOutOfBoundsException: begin 0, end -2, length 29 at java.base/java.lang.String.checkBoundsBeginEnd(Unknown Source) at java.base/java.lang.String.substring(Unknown Source) at com.amazon.aws.partners.saasfactory.saasboost.OnboardingService.processValidateOnboardingQueue(OnboardingService.java:1260) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) at java.base/java.lang.reflect.Method.invoke(Unknown Source)
```
### Reproduction Steps

1. [install-using-cloud9.md](https://github.com/awslabs/aws-saas-boost/blob/main/docs/install-using-cloud9.md) 
2. [deploy-the-sample-application](https://github.com/awslabs/aws-saas-boost/blob/main/docs/getting-started.md#step-7---optional-deploy-the-sample-application)
3. [build-and-deploy-the-sample-application](https://github.com/awslabs/aws-saas-boost/blob/main/docs/getting-started.md#build-and-deploy-the-sample-application)
4. [onboard-a-tenant](https://github.com/awslabs/aws-saas-boost/blob/main/docs/getting-started.md#onboard-a-tenant)

### What did you expect to happen?

Completion of Onboarding creation.

### What actually happened?

Validating status does not change after Onboarding is created.

### Environment

  - **AWS Region  :ap-northeast-1**
  - **AWS SaaS Boost Version :Version v2.2.3-6@452d7ca**
  - **Workload OS  (Linux or Windows) :**

### Other

--- 

This is :bug: Bug Report

**Comment by YutaOkoshi** [comment]
Maybe this change will have an impact
https://github.com/awslabs/aws-saas-boost/commit/452d7ca8902e7338e999290eebad9062c342915f

**Comment by brtrvn** [comment]
@YutaOkoshi that error is coming from the section of validation checking the Route53 Hosted Zone for duplicate tenant subdomains. There must be an A Record in the HostedZone for that tenant with an unexpected structure. You can find the hosted zone by looking at the appConfig and then run `aws route53 list-resource-record-sets --hosted-zone-id YOUR_HOSTED_ZONE_ID` to see what the output looks like.

**Comment by YutaOkoshi** [comment]
@brtrvn 
thanks for comment.
I re-created the Application and it worked.
Probably because the Domain Name and Hosted Zone of the Application were unintentionally specified.

If Validation finds something error, the end user may wait forever without an error message and may not know where to fix it.
Therefore, it would be beneficial to end users if error messages are output.
